from io import StringIO
from collections import deque
from util import cstr, COLOR, FORMAT


# inp = StringIO("""\
# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# """)
inp = open("input.txt")

first = inp.readline()
height, width = 1, len(first)
grid = set()
for row, r in enumerate(inp, start=1):
    height += 1
    grid.update((row, col) for col, c in enumerate(r) if c == "^")

prev_row = [1 if c == first.index("S") else 0 for c in range(width)]
for r in range(height):
    row = [0] * width
    for c in range(width):
        if (r, c) in grid:
            row[c - 1] += prev_row[c]
            row[c + 1] += prev_row[c]
        else:
            row[c] += prev_row[c]
    prev_row = row

assert(sum(prev_row) == 73007003089792)
